name: 🔀 Plugin repository

on:
  repository_dispatch:
    types: [ merge-plugins ]

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - run: >
          echo ${{ github.event.client_payload.name }}
          echo ${{ github.event.client_payload.version }}
          echo ${{ github.event.client_payload.url }}

      - name: Get source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.CI_BOT_PAT }}  # Important to launch CI on a commit from a bot

      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install qgis-plugin-repo
        run: pip3 install qgis-plugin-repo

      - name: Merge
        run: qgis-plugin-repo merge ${{ github.event.client_payload.url }} plugins.xml

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Publish QGIS Plugin ${{ github.event.client_payload.name }} ${{ github.event.client_payload.version }}"
